### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by godsplanhk** [godsplanhk/CUXAM#3]
I have seen some flaws in design element in login page itself and major issue a flet is that the application is not responsive. 
1.Login container can be improved
2.Dark theme looks good but in light theme there is lots of vibrance in colors, so I would recommend using snow white or bone white instead of using plain white color as a background.
4.When the submit is clicked it takes 3-5 sec to get logged in. Till then there is no action on the page. So i would like to add so that user may know there is something happening in the backend.

Overall responsive design needs to be improved, so that the application works fine in the device with any screen size.
These are some initial issue that I experienced as a user and others might face

**Comment by httpsabhi** [comment]
These are some initial observations based on my user experience. I believe addressing these issues could significantly enhance the overall user experience of the application.

**Comment by godsplanhk** [comment]
i appreciate that, i am transferring the issue to you. feel free to seek any help if needed.

**Comment by godsplanhk** [comment]
![Screenshot_2024-06-02-07-30-10-00_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/godsplanhk/CUXAM/assets/119732088/10606eff-d633-4615-b986-c317789644c8)

**Comment by godsplanhk** [comment]
@httpsabhi the mode toggle seems to be little bit off can you please look into this issue

**Comment by httpsabhi** [comment]
okay i will

**Comment by godsplanhk** [comment]
![image](https://github.com/godsplanhk/CUXAM/assets/119732088/3d105550-9ab1-4146-b60a-9e2edf03e203)
@httpsabhi can you please make the generate page responsive, buttons some time goes out of the grid.

**Comment by httpsabhi** [comment]
Yes, I can. For that I need to access the database which I am unable to do.
Help me in that case.

**Comment by godsplanhk** [comment]
inactive
